---
- name: Shutdown kafka Connect 
  hosts: target
  gather_facts: no
  tasks:
    - name: Find and send kill signal
      become: yes
      command: pgrep -f "org.apache.kafka.connect.cli.ConnectDistributed" | xargs kill -SIGTERM

